@startmindmap
* SW Project
** Development Process
*** General
**** Language
**** Management Tools
***** JIRA
***** Confluence
***** Codebeamer
*** System Definition
**** System Boundaries
**** Children Elements\nHW/SW/Mechanics
**** SW Unit\nDefinition
**** Roles
**** Responsibilities
**** Namespaces
*** Requirements
**** Features
**** Interfaces
***** Communication\nInterfaces
***** SW Interfaces
***** HW/SW Interfaces
***** Mechanical Interfaces
**** HSI
***** Requests from SW to HW
****** Pins
****** Memory
****** ASIL Rating
***** Requests from HW to SW
**** ASIL
**** Homologation
**** Reporter/nAssignee
**** Quality Checks
***** Checker Bot
**** Derivation
*** Implementation
*** Release Management
**** Tag/SW Logistics
**** Change Logs
***** Pull Requests
***** Commits
***** Tickets
** Toolchain & CI
*** Build Environment
**** Bazel
**** CMake/Make
**** Tools
***** Compiler
***** A2L Tool (XCP)
*** Clang
**** Tidy (Naming\nConvention)
**** Format (Code\nFormation)
*** Doxygen
*** Version Control
**** Git/GitHub
*** Continuous\nIntegration
**** Protected\nBranches
** Microcontroller
*** TRM (Technical\nReference\nManual)
*** Architecture
**** Cores
**** Busses
**** Peripherals
*** Memory Map
*** Protected Areas
*** ERRATA
** Code & Workspace
*** Naming Conventions
**** Files
**** Folders
**** Symbols
** Documentation
*** Markdown
**** ReadMe
*** PlantUML
** Testing
*** Code Debug Tool\n(e.g. GCC)
*** Unit Test
**** CUnit
**** GooleTest
*** Smoke Tests
**** Flash Test
**** Reset Test
@endmindmap
