cc_library(
    name = "mcal_f28p65x_inc_h",
    srcs = glob(["*.h"]),
    deps = [
        "//toolchain:c2000_builtin_directories",
    ],
    includes = ["."],
    visibility = ["//f28p65/mcal:__subpackages__"],
)
