cc_library(
    name = "sysHwCfg_app",
    srcs = glob(["*.c"]),
    hdrs = glob(["*.h"]),
    deps = [
        "//f2838/mcal:mcal_f2838x",
        "//f2838/public:public_types_h",
    ],
    includes = ["."],
    visibility = ["//f2838/units/sysHwCfg:__subpackages__"],
)