cc_library(
    name = "free_rtos_c28x",
    srcs = glob(["*.c"]),
    deps = [
        "//f2838/os/include:free_rtos_c28x_include",
        "//f2838/os/portable:free_rtos_c28x_portable",
    ],
    includes = ["."],
    visibility = ["//f2838/os:__subpackages__"],
)