cc_library(
    name = "units_app",
    deps = [
        "//machine/evalBoard/tmdscncd28p65x/units/sysHwCfg:sysHwCfg_app",
    ],
    includes = ["."],
    visibility = ["//machine/evalBoard/tmdscncd28p65x/swe/app:__subpackages__"],
)