cc_library(
    name = "task10msQm",
    srcs = glob(["*.c"]),
    hdrs = glob(["*.h"]),
    deps = [
        "//f28p65/public:public_types_h",
        "//platforms/c28/os:free_rtos_c28x_app",
    ],
    includes = ["."],
    visibility = ["//f28p65/swe/app:__subpackages__"],
)
