# Example AVR binary
cc_binary(
    name = "app",
    srcs = ["main.c"],
    copts = [
        "-mmcu=atmega32u4",
        "-DF_CPU=16000000UL",
    ],
    linkopts = [
        "-mmcu=atmega32u4",
    ],
    deps = [],
)
