cc_library(
    name = "free_rtos_c28x_include",
    hdrs = glob(["*.h"]),
    deps = [
        "//toolchain:c2000_builtin_directories",
    ],
    includes = ["."],
    visibility = ["//f2838/os:__subpackages__"],
)
