# Collect all .c and .h files
filegroup(
    name = "source_files",
    # srcs = glob(
    srcs =
        [
            "arduinoLeonardo/main.c",
            # "**/*.h",
        ],
        # allow_empty = True,
    # ),
    visibility = ["//visibility:public"],
)