cc_library(
    name = "public_types_h",
    srcs = [],
    hdrs = glob(["*.h"]),
    deps = [
        "//toolchain:c2000_builtin_directories",
    ],
    includes = ["."],
    visibility = ["//f28p65:__subpackages__"],
)
