cc_library(
    name = "sysHwCfg_app",
    deps = [
        "//machine/evalBoard/tmdscncd28p65x/units/sysHwCfg/app:sysHwCfg_app",
    ],
    includes = ["."],
    visibility = ["//machine/evalBoard/tmdscncd28p65x/units:__subpackages__"],
)