cc_library(
    name = "free_rtos_c28x_app",
    srcs = glob(["*.c"]),
    deps = [
        "//f28p65/os/include:free_rtos_c28x_include",
        "//f28p65/os/portable:free_rtos_c28x_portable",
    ],
    includes = ["."],
    visibility = ["//f28p65:__subpackages__"],
)