cc_library(
    name = "public_types_h",
    srcs = [],
    hdrs = glob(["*.h"]),
    deps = [
        "//toolchain/c28:c2000_builtin_directories",
    ],
    includes = ["."],
    visibility = ["//machine/evalBoard/tmdscncd28p65x:__subpackages__"],
)
