cc_library(
    name = "public_types_h",
    srcs = [],
    hdrs = glob(["*.h"]),
    deps = [
        "//platforms/c2000:platform_types_h",
    ],
    includes = ["."],
    visibility = ["//machine/evalBoard/tmdscncd28p65x:__subpackages__"],
)
