cc_library(
    name = "mcal_f2838x_inc_h",
    srcs = glob(["*.h"]),
    deps = [
        "//toolchain:c2000_builtin_directories",
    ],
    includes = ["."],
    visibility = ["//f2838/mcal:__subpackages__"],
)