cc_library(
    name = "task10msQm",
    srcs = glob(["*.c"]),
    hdrs = glob(["*.h"]),
    deps = [
        "//f2838/public:public_types_h",
        "//f2838/os/portable:free_rtos_c28x_portable",
    ],
    includes = ["."],
    visibility = ["//f2838/swe/app:__subpackages__"],
)
