# Format: path | config | bazel_target
# Lines starting with # are comments

machine/evalBoard/tmdscncd28p65x | c2000 | //machine/evalBoard/tmdscncd28p65x/swe/app
machine/sumobotBlackMagic | atmega32u4 | //machine/sumobotBlackMagic:app
